#!/bin/bash

#$ -N MIDAS_test                     #-- set the name of the job; this will appear in the job listing
#$ -l h_vmem=2G                      #-- set the maximum memory usage (per slot). on scg3 the default is 1GB of h_vmem per slot
#$ -l h_rt=168:00:00                 #-- set the maximum run time, hh:mm:ss, default is 6hrs on scg3
#$ -w e                              #-- check for errors in the job submission options
#$ -j y                              #-- join the stdout and stderr streams into one file
#$ -o ~/output_error_directory       #-- output directory 
#$ -e ~/output_error_directory       #-- error directory   
#$ -t 1-1                           #-- specify the number of tasks 

#readarray files < ~/snyder_project/timepts.txt
#files=(null ${files[@]}) # this pads the file with an extra line in the beginning.
#timept=${files[$SGE_TASK_ID]}

#echo $timept

source /home/ngarud/snyder_project_2/bin/activate # this activates the python environment I need to run the scripts

export PYTHONPATH=/home/ngarud/snyder_project_2/lib/python2.7/site-packages:/home/ngarud/snyder_project/software/MIDAS:$PYTHONPATH
export PYTHONPATH=$PYTHONPATH:/home/ngarud/snyder_project/software/MIDAS
export PATH=$PATH:/home/ngarud/snyder_project/software/MIDAS/scripts
export MIDAS_DB=/home/ngarud/snyder_project/software/midas_db_v1.2

file=700013715
OUTDIR=/home/ngarud/snyder_project/MIDAS_test/${file}
mkdir $OUTDIR
indir=/home/ngarud/snyder_project/MIDAS_test

echo 'species'
run_midas.py species $OUTDIR -1 $indir/${file}_1_test.fastq.gz -2 $indir/${file}_2_test.fastq.gz



/home/ngarud/snyder_project_2/lib/python2.7/site-packages:/home/ngarud/snyder_project_2/bin:/srv/gsfs0/software/python/2.7.9/bin:/srv/gsfs0/software/gnu/gcc/5.2.0/bin:/srv/gsfs0/admin_stuff/soge-8.1.8/bin:/srv/gsfs0/admin_stuff/soge-8.1.8/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ganglia/bin:/opt/ganglia/sbin:/usr/java/latest/bin:/opt/rocks/bin:/opt/rocks/sbin:/home/ngarud/snyder_project/software/MIDAS/scripts